### ISSUE TITLE
Error when Results folder already exists

### ISSUE THREAD

**Issue by davidrudduck** [orlikoski/CDQR#37]
Recently built Ubuntu 16.04 Server LTS image, using the Skadi signed in installer [as at 21/03/2019].

When attempting to run cdqr.py when there is already a Results folder, the following error is displayed:

`david@skadi:~$ cdqr.py -p datt --max_cpu --es_kb HCS -z CYLRTRIAGEIMAGE.zip
CDQR Version: 4.3
Plaso Version: 20190131
WARNING!! Known compatible version of Plaso NOT detected. Attempting to use default parser list. Try using the --no_dependencies_check if Plaso dependancies are the issue.
Using parser: datt
Number of cpu cores to use: 2
Traceback (most recent call last):
  File "/usr/local/bin/cdqr.py", line 1771, in <module>
    main()
  File "/usr/local/bin/cdqr.py", line 1684, in main
    if not query_yes_no("\n"+dst_loc+" already exists.  Would you like to use that directory anyway?","yes"):
  File "/usr/local/bin/cdqr.py", line 672, in query_yes_no
    if args.confirmAll:
NameError: name 'args' is not defined
`

**Comment by orlikoski** [comment]
Issue should be fixed now

**Comment by davidrudduck** [comment]
Confirmed fixed :)
