### ISSUE TITLE
cdqr breaks on unicode characters

### ISSUE THREAD

**Issue by davidrudduck** [orlikoski/CDQR#39]
Running cdqr v.4.4.0 via skadi 2019.2 docker setup.

CDQR exits with unable to extract. 

> david@skadi:~$ cdqr in:CASE-DEVICE.zip out:CASE-DEVICE -p datt -z --max_cpu --es_kb CASE-DEVICE --es_ts CASE-DEVICE
> docker run   -v /etc/hosts:/etc/hosts:ro   --network host -v /home/david/CASE-DEVICE.zip:home/david/CASE-DEVICE.zip -v /home/david/CASE-DEVICE:/home/david/CASE-DEVICE -v /etc/timesketch.conf:/etc/timesketch.conf aorlikoski/cdqr:4.4.0 -y /home/david/CASE-DEVICE.zip /home/david/CASE-DEVICE -p datt -z --max_cpu --es_kb CASE-DEVICE --es_ts CASE-DEVICE
> CDQR Version: 4.4
> Plaso Version: 20190131
> WARNING!! Known compatible version of Plaso NOT detected. Attempting to use default parser list. Try using the --no_dependencies_check if Plaso dependancies are the issue.
> Using parser: datt
> Number of cpu cores to use: 4
> Destination Folder: /home/david/CASE-DEVICE
> Attempting to extract source file: /home/david/CASE-DEVICE.zip
> Unable to extract file: /home/david/CASE-DEVICE.zip
> 'ascii' codec can't encode character '\u2310' in position 135: ordinal not in range(128)

**Comment by orlikoski** [comment]
Looks like there is an issue with the python unzip library and not an issue with CDQR coding itself. Recommend users unzip manually files that affected by the issue with python while how to get around it is researched

**Comment by orlikoski** [comment]
@davidrudduck does the zip file get unzipped correctly by `unzip` or other tools?

**Comment by davidrudduck** [comment]
@orlikoski yes, `unzip` worked fine.

my CyLR collection list is a lot longer than the defaults so it's possible that one of the files I collect is unicode encoded and causing grief to the python based unzip library.

**Comment by orlikoski** [comment]
Definitely good to know and this issue getting documented will help others who have run into the same problem as well as a solution to it. If it becomes a major issue we can research other options than the python zip library

**Comment by schoad** [comment]
Same issue: Files collected with CyLR. Unzipping works fine with unzip and other tools (e.g. Windows, WinRAR,...).

`'ascii' codec can't encode character '\xfc' in position 121: ordinal not in range(128)
`
Command used: 
`cdqr in:COMPUTERNAME.zip out:Results_test -z --max_cpu -p win
`

**Comment by jhill-cmd** [comment]
Just encountered the same issue with the docker version. Didn't understand how to solve it ?
```
user:/$ ./cdqr in:laptop out:Results_laptop -p win -z --max_cpu
Assigning CDQR to the host network
The Docker network can be changed by modifying the "DOCKER_NETWORK" environment variable
Example (default Skadi mode): export DOCKER_NETWORK=host
Example (use other Docker network): export DOCKER_NETWORK=skadi-backend
docker run  --network host  -v /home/user/tools/laptop/:/home/user/tools/laptop/ -v /home/user/tools/Results_laptop:/home/user/tools/Results_laptop aorlikoski/cdqr:5.0.0 -y /home/user/tools/laptop/ /home/user/tools/Results_laptop -z --max_cpu
CDQR Version: 5.0
Plaso Version: 20190331
Using parser: win
Number of cpu cores to use: 4
Destination Folder: /home/user/tools/Results_laptop
Attempting to extract source file: /home/user/tools/laptop
Unable to extract file: /home/user/tools/laptop
[Errno 21] Is a directory: '/home/user/tools/laptop'

```
