### ISSUE TITLE
Bypass pause at the end of CDQR processing

### ISSUE THREAD

**Issue by pcsifu** [orlikoski/CDQR#42]
Alan, can you please add a switch to allow users to bypass the pause at the end of running CDQR.  As you are aware I have included CDQR in my scripting processes.  I have automated CaseFramework processing (with the exception of volatility setup prior to processing which requires minimal user interaction).  By bypassing the pause it would allow me to continue additional processing without requiring the user to press any key to continue.

**Comment by orlikoski** [comment]
Does the `-y` flag not do this already?

https://github.com/orlikoski/CDQR/blob/master/src/cdqr.py#L1579
