### ISSUE TITLE
CDQR does not parse Windows Event correctly to Kibana

### ISSUE THREAD

**Issue by mrezqi** [orlikoski/CDQR#57]
Hi, I tried to parse CyLR output using CDQR to Skadi. This was from a windows target machine. After parsing, it seems like windows event logs were not parsed completely. 

The main column such as timestamp and event id were correct but the XML strings were left as it is in one giant column. Is this not supported yet in the current version?

**Comment by davidrudduck** [comment]
This is more to do with how Plaso (specifically psort) handles export to ElasticSearch and less to do with how CDQR works.

CDQR is really just an advanced wrapper script for log2timeline and psort (Plaso).

**Comment by mrezqi** [comment]
Thanks David, I'll close this issue and check with the log2timeline guys.
